// <auto-generated />
using System;
using DarkKitchen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DarkKitchen.Data.Migrations
{
    [DbContext(typeof(DarkKitchenDbContext))]
    [Migration("20260708022257_OrderSeedingFixed")]
    partial class OrderSeedingFixed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DarkKitchen.Data.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jonathan@example.com",
                            Name = "Jonathan"
                        },
                        new
                        {
                            Id = 2,
                            Email = "paula@example.com",
                            Name = "Paula"
                        },
                        new
                        {
                            Id = 3,
                            Email = "takis@example.com",
                            Name = "Takis"
                        },
                        new
                        {
                            Id = 4,
                            Email = "lemon@example.com",
                            Name = "Lemon"
                        },
                        new
                        {
                            Id = 5,
                            Email = "bhy@example.com",
                            Name = "Bahji"
                        });
                });

            modelBuilder.Entity("DarkKitchen.Data.Entities.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Traditional Latin American custard dessert popular in countries like Peru, Chile, and Colombia. Similar to flan or crème brûlée.",
                            Enabled = true,
                            Name = "Leche Asada",
                            OriginCountry = "Chile",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Round, deep-fried cheese fritters that are crispy on the outside and soft and airy on the inside.",
                            Enabled = true,
                            Name = "Colombian Buñuelos",
                            OriginCountry = "Colombia",
                            Price = 0m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Traditional, creamy rice pudding",
                            Enabled = true,
                            Name = "Arroz con leche",
                            OriginCountry = "Spain",
                            Price = 0m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Classic Latin American pastry made by folding dough into a half-moon shape, filling it with melty cheese, and deep-frying it until the exterior is crispy and the inside is gooey.",
                            Enabled = true,
                            Name = "Fried cheese empanadas",
                            OriginCountry = "Mexico",
                            Price = 0m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Iconic, ultra-rich dessert renowned for its dense, velvety texture.",
                            Enabled = true,
                            Name = "New York cheesecake",
                            OriginCountry = "United States",
                            Price = 0m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Rich, comforting pasta dish consisting of long, flat fettuccine noodles coated in a velvety, indulgent sauce.",
                            Enabled = true,
                            Name = "Fettucine alfredo",
                            OriginCountry = "Italy",
                            Price = 0m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Savory Latin American casserole. It features a base of seasoned ground beef (pino) layered with hard-boiled eggs, black olives, and raisins.",
                            Enabled = true,
                            Name = "Potato Pie",
                            OriginCountry = "Chile",
                            Price = 0m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Traditional Dutch bite-sized snacks consisting of a rich, thick meat ragout enveloped in a crispy, deep-fried breadcrumb crust.",
                            Enabled = true,
                            Name = "Bitterballen",
                            OriginCountry = "Netherlands",
                            Price = 0m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Classic Middle Eastern dish. It features crispy, toasted pita bread combined with warm ingredients and creamy sauces.",
                            Enabled = true,
                            Name = "Fatteh",
                            OriginCountry = "Egypt",
                            Price = 0m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Southern-style, pressure-fried chicken. Each piece is coated in a proprietary blend of 11 herbs and spices, resulting in a signature golden-brown, crispy exterior that shatters upon the first bite, giving way to piping-hot, exceptionally tender and juicy meat.",
                            Enabled = true,
                            Name = "Kentucky Fried Chicken",
                            OriginCountry = "United States",
                            Price = 0m
                        });
                });

            modelBuilder.Entity("DarkKitchen.Data.Entities.DishIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(10, 3)
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("IngredientId");

                    b.ToTable("DishIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DishId = 1,
                            IngredientId = 4,
                            Quantity = 0.25m
                        },
                        new
                        {
                            Id = 2,
                            DishId = 1,
                            IngredientId = 8,
                            Quantity = 4m
                        },
                        new
                        {
                            Id = 3,
                            DishId = 1,
                            IngredientId = 6,
                            Quantity = 0.2m
                        },
                        new
                        {
                            Id = 4,
                            DishId = 2,
                            IngredientId = 8,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 5,
                            DishId = 2,
                            IngredientId = 11,
                            Quantity = 0.2m
                        },
                        new
                        {
                            Id = 6,
                            DishId = 2,
                            IngredientId = 6,
                            Quantity = 0.1m
                        },
                        new
                        {
                            Id = 7,
                            DishId = 2,
                            IngredientId = 3,
                            Quantity = 0.002m
                        },
                        new
                        {
                            Id = 8,
                            DishId = 2,
                            IngredientId = 4,
                            Quantity = 0.1m
                        },
                        new
                        {
                            Id = 9,
                            DishId = 3,
                            IngredientId = 1,
                            Quantity = 0.2m
                        },
                        new
                        {
                            Id = 10,
                            DishId = 3,
                            IngredientId = 2,
                            Quantity = 0.4m
                        },
                        new
                        {
                            Id = 11,
                            DishId = 3,
                            IngredientId = 4,
                            Quantity = 0.8m
                        },
                        new
                        {
                            Id = 12,
                            DishId = 3,
                            IngredientId = 3,
                            Quantity = 0.001m
                        },
                        new
                        {
                            Id = 13,
                            DishId = 3,
                            IngredientId = 5,
                            Quantity = 0.05m
                        },
                        new
                        {
                            Id = 14,
                            DishId = 3,
                            IngredientId = 6,
                            Quantity = 0.2m
                        },
                        new
                        {
                            Id = 15,
                            DishId = 3,
                            IngredientId = 7,
                            Quantity = 12m
                        },
                        new
                        {
                            Id = 16,
                            DishId = 4,
                            IngredientId = 9,
                            Quantity = 0.6m
                        },
                        new
                        {
                            Id = 17,
                            DishId = 4,
                            IngredientId = 3,
                            Quantity = 0.05m
                        },
                        new
                        {
                            Id = 18,
                            DishId = 4,
                            IngredientId = 4,
                            Quantity = 0.02m
                        },
                        new
                        {
                            Id = 19,
                            DishId = 4,
                            IngredientId = 8,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 20,
                            DishId = 4,
                            IngredientId = 11,
                            Quantity = 0.4m
                        },
                        new
                        {
                            Id = 21,
                            DishId = 5,
                            IngredientId = 5,
                            Quantity = 0.1m
                        },
                        new
                        {
                            Id = 22,
                            DishId = 5,
                            IngredientId = 6,
                            Quantity = 0.4m
                        },
                        new
                        {
                            Id = 23,
                            DishId = 5,
                            IngredientId = 11,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 24,
                            DishId = 5,
                            IngredientId = 9,
                            Quantity = 0.1m
                        },
                        new
                        {
                            Id = 25,
                            DishId = 5,
                            IngredientId = 8,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 26,
                            DishId = 6,
                            IngredientId = 16,
                            Quantity = 0.3m
                        },
                        new
                        {
                            Id = 27,
                            DishId = 6,
                            IngredientId = 5,
                            Quantity = 0.1m
                        },
                        new
                        {
                            Id = 28,
                            DishId = 6,
                            IngredientId = 9,
                            Quantity = 0.01m
                        },
                        new
                        {
                            Id = 29,
                            DishId = 6,
                            IngredientId = 11,
                            Quantity = 0.1m
                        },
                        new
                        {
                            Id = 30,
                            DishId = 6,
                            IngredientId = 17,
                            Quantity = 0.25m
                        },
                        new
                        {
                            Id = 31,
                            DishId = 7,
                            IngredientId = 12,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 32,
                            DishId = 7,
                            IngredientId = 5,
                            Quantity = 0.1m
                        },
                        new
                        {
                            Id = 33,
                            DishId = 7,
                            IngredientId = 3,
                            Quantity = 0.02m
                        },
                        new
                        {
                            Id = 34,
                            DishId = 7,
                            IngredientId = 8,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 35,
                            DishId = 7,
                            IngredientId = 15,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 36,
                            DishId = 7,
                            IngredientId = 13,
                            Quantity = 3m
                        },
                        new
                        {
                            Id = 37,
                            DishId = 7,
                            IngredientId = 14,
                            Quantity = 0.3m
                        },
                        new
                        {
                            Id = 38,
                            DishId = 8,
                            IngredientId = 5,
                            Quantity = 0.1m
                        },
                        new
                        {
                            Id = 39,
                            DishId = 8,
                            IngredientId = 9,
                            Quantity = 0.2m
                        },
                        new
                        {
                            Id = 40,
                            DishId = 8,
                            IngredientId = 15,
                            Quantity = 0.5m
                        },
                        new
                        {
                            Id = 41,
                            DishId = 8,
                            IngredientId = 14,
                            Quantity = 0.5m
                        },
                        new
                        {
                            Id = 42,
                            DishId = 8,
                            IngredientId = 3,
                            Quantity = 0.03m
                        },
                        new
                        {
                            Id = 43,
                            DishId = 8,
                            IngredientId = 8,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 44,
                            DishId = 9,
                            IngredientId = 14,
                            Quantity = 0.3m
                        },
                        new
                        {
                            Id = 45,
                            DishId = 9,
                            IngredientId = 15,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 46,
                            DishId = 9,
                            IngredientId = 13,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 47,
                            DishId = 9,
                            IngredientId = 1,
                            Quantity = 0.5m
                        },
                        new
                        {
                            Id = 48,
                            DishId = 9,
                            IngredientId = 5,
                            Quantity = 0.1m
                        },
                        new
                        {
                            Id = 49,
                            DishId = 9,
                            IngredientId = 3,
                            Quantity = 0.01m
                        },
                        new
                        {
                            Id = 50,
                            DishId = 10,
                            IngredientId = 10,
                            Quantity = 2m
                        },
                        new
                        {
                            Id = 51,
                            DishId = 10,
                            IngredientId = 8,
                            Quantity = 1m
                        },
                        new
                        {
                            Id = 52,
                            DishId = 10,
                            IngredientId = 9,
                            Quantity = 0.5m
                        },
                        new
                        {
                            Id = 53,
                            DishId = 10,
                            IngredientId = 6,
                            Quantity = 0.01m
                        },
                        new
                        {
                            Id = 54,
                            DishId = 10,
                            IngredientId = 3,
                            Quantity = 0.01m
                        });
                });

            modelBuilder.Entity("DarkKitchen.Data.Entities.FulfillmentEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FulfilledAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FulfillmentEvents");
                });

            modelBuilder.Entity("DarkKitchen.Data.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("Stock")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Unit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "White Rice",
                            Stock = 5m,
                            Unit = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "Water",
                            Stock = 20m,
                            Unit = 3
                        },
                        new
                        {
                            Id = 3,
                            Name = "Salt",
                            Stock = 1m,
                            Unit = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Milk",
                            Stock = 5m,
                            Unit = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Butter",
                            Stock = 1m,
                            Unit = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sugar",
                            Stock = 2m,
                            Unit = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Condensed Milk",
                            Stock = 50m,
                            Unit = 0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Egg",
                            Stock = 50m,
                            Unit = 4
                        },
                        new
                        {
                            Id = 9,
                            Name = "Flour",
                            Stock = 5m,
                            Unit = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Chicken",
                            Stock = 5m,
                            Unit = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cheese",
                            Stock = 8m,
                            Unit = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "Potato",
                            Stock = 6m,
                            Unit = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "Tomato",
                            Stock = 15m,
                            Unit = 4
                        },
                        new
                        {
                            Id = 14,
                            Name = "Ground Beef",
                            Stock = 3m,
                            Unit = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "Onion",
                            Stock = 10m,
                            Unit = 4
                        },
                        new
                        {
                            Id = 16,
                            Name = "Cream",
                            Stock = 5m,
                            Unit = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "Pasta",
                            Stock = 3m,
                            Unit = 2
                        });
                });

            modelBuilder.Entity("DarkKitchen.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 3,
                            Priority = 0,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 2,
                            Priority = 0,
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedUtc = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerId = 5,
                            Priority = 1,
                            Status = 1
                        });
                });

            modelBuilder.Entity("DarkKitchen.Data.Entities.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DishId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DishId = 5,
                            OrderId = 1,
                            Quantity = 2
                        },
                        new
                        {
                            Id = 2,
                            DishId = 6,
                            OrderId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 3,
                            DishId = 1,
                            OrderId = 2,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            DishId = 4,
                            OrderId = 3,
                            Quantity = 1
                        },
                        new
                        {
                            Id = 5,
                            DishId = 8,
                            OrderId = 3,
                            Quantity = 3
                        });
                });

            modelBuilder.Entity("DarkKitchen.Data.Entities.DishIngredient", b =>
                {
                    b.HasOne("DarkKitchen.Data.Entities.Dish", "Dish")
                        .WithMany("Ingredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarkKitchen.Data.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("DarkKitchen.Data.Entities.Order", b =>
                {
                    b.HasOne("DarkKitchen.Data.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DarkKitchen.Data.Entities.OrderLine", b =>
                {
                    b.HasOne("DarkKitchen.Data.Entities.Dish", "Dish")
                        .WithMany()
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DarkKitchen.Data.Entities.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("DarkKitchen.Data.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DarkKitchen.Data.Entities.Dish", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("DarkKitchen.Data.Entities.Order", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
